### ISSUE TITLE
Plugin legacy name may be removed in a future version

### ISSUE THREAD

**Issue by prov3it** [hsmade/certbot-dns-transip#27]
Im getting a warning when requesting certificates using this plugin:

Plugin legacy name certbot-dns-transip:dns-transip may be removed in a future version. Please use dns-transip instead.

For more information about this, i would like to refer to [this](https://github.com/linuxserver/docker-swag/issues/51) issue. 

changes that need to be made are simple. transip.ini has to look like [this](https://github.com/linuxserver/docker-swag/pull/48/commits/87cdcfdb189dd8386cede09c7e36ac7be7c638e1#diff-eef2a00a038caafa3d366e80c21205351208983b19233384509a119da5805d7a): 

dns_transip_username = <transip_username>
dns_transip_key_file = /config/dns-conf/transip-rsa.key

Im not good with github, pull requests etc, but i would like to contribute by reporting this issue.

**Comment by hsmade** [comment]
Hi, and thanks for your issue! Is this just about the example for the `transip.ini` file, or is there more that needs to be changed?

**Comment by prov3it** [comment]
Im not sure. As far as i know it is. May be @aptalca can confirm that.

**Comment by hsmade** [comment]
I did update the docs already. So let me know if anything else is needed

**Comment by aptalca** [comment]
@hsmade the plugin name in the certbot arguments also need to be updated:
```
docker run -ti -v `/tmp/letsencrypt`:/etc/letsencrypt \
    hsmade/certbot-transip \
    certonly -n \
    -d 'your.domain.com' \
    -a dns-transip \
    --dns-transip-credentials /etc/letsencrypt/transip.ini \
    --dns-transip-propagation-seconds 240 \
    -m your@domain.com \
    --agree-tos \
    --eff-email
```

**Comment by hsmade** [comment]
fixed in 0.3.3
Thanks for the help peeps!

**Comment by eakoning** [comment]
@siccovansas and @hsmade I'm still getting the warning in version 4.12.0 of the Let's Encrypt add-on in Home Assistant. Is there something I need to change in the configuration of the add-on?
